// register.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatInputModule } from '@angular/material/input';
import { MatFormFieldModule } from '@angular/material/form-field';
import { ReactiveFormsModule, FormGroup, FormControl, Validators } from '@angular/forms';
import {MatGridListModule} from "@angular/material/grid-list";
import {AuthenticationService} from "../../services/authentication.service";
import {Router} from "@angular/router";
import {MatSnackBar} from "@angular/material/snack-bar";
import {BenefactorsService} from "../../services/benefactors.service";
import {Benefactor} from "../../models/benefactor";
import {UsersService} from "../../services/users.service";
import {User} from "../../models/user";
import {Address} from "../../models/address";

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [
    CommonModule,
    MatButtonModule,
    MatCardModule,
    MatInputModule,
    MatFormFieldModule,
    ReactiveFormsModule,
    MatGridListModule,
  ],
  templateUrl: './user-register.component.html',
  styleUrls: ['./user-register.component.css']
})
export class UserRegisterComponent {
  constructor(
    protected userService: UsersService,
    private router: Router,
    private snackBar: MatSnackBar
  ) { }
  registerForm = new FormGroup({
    firstName: new FormControl('', [Validators.required]),
    lastName: new FormControl('', [Validators.required]),
    username: new FormControl('', [Validators.required]),
    email: new FormControl('', [Validators.required, Validators.email]),
    password: new FormControl('', [Validators.required, Validators.minLength(6)]),
    confirmPassword: new FormControl('', [Validators.required, Validators.minLength(6)]),
    phone: new FormControl(''),
    street: new FormControl(''),
    city: new FormControl(''),
    postalCode: new FormControl(''),
    country: new FormControl('')
  });

  onSubmit() {
    if (this.registerForm.valid) {
      const newUser = new User(
        '', // id will be generated by the backend
        this.registerForm.controls['lastName'].value || '',
        this.registerForm.controls['firstName'].value || '' ,
        this.registerForm.controls['username'].value || '',
        this.registerForm.controls['email'].value || '',
        this.registerForm.controls['password'].value || '',
        '', // image not handled here
        new Date(), // createdAt
        new Date(), // updatedAt
        [], // roles, assuming empty array for now
        new Address(
          this.registerForm.controls['street'].value || '',
          this.registerForm.controls['city'].value || '',
          this.registerForm.controls['postalCode'].value || '',
          this.registerForm.controls['country'].value || ''
        ),
        this.registerForm.controls['phone'].value || '',
        0, // leafs, assuming default value
        'en', // language, assuming default value
        [], // title, assuming empty array for now
        true, // notify, assuming true for now
        true // active, assuming true for now
      );
      this.userService.addUser(newUser)
        ?.subscribe(
          response => {
            this.snackBar.open('User Registered Successfully', 'Close', {
              duration: 3000,
            }).afterDismissed().subscribe(() => {
              // Navigate only after the snackbar is dismissed
              this.router.navigate(['users/login']);
            });
          },
          error => {
            this.snackBar.open(error.error.message, 'Close', {
              duration: 3000,
            });
          }
        );
    }
  }
}
